"""
Data Export API — download datasets, reports, and analytics as CSV/JSON.
"""
import io
import json
import logging
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from core.database import get_db, Dataset, Report, InsightResult, AuditLog
from core.auth import get_current_user, CurrentUser
from core.security import record_audit
from api.routes.data import _read_csv_safe

log = logging.getLogger(__name__)

router = APIRouter(prefix="/export", tags=["export"])


@router.get("/dataset/{dataset_id}")
async def export_dataset(
    dataset_id: str,
    format: str = Query("csv", description="csv or json"),
    user: CurrentUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Download a dataset as CSV or JSON."""
    result = await db.execute(
        select(Dataset).where(Dataset.id == dataset_id, Dataset.org_id == user.org_id)
    )
    ds = result.scalar_one_or_none()
    if not ds:
        raise HTTPException(404, "Dataset not found")

    df = _read_csv_safe(Path(ds.filepath), nrows=None)

    await record_audit(db, user.org_id, user.user_id, "export", "dataset", dataset_id, f"format={format}")
    await db.commit()

    if format == "json":
        data = df.to_json(orient="records", date_format="iso")
        return StreamingResponse(
            io.BytesIO(data.encode("utf-8")),
            media_type="application/json",
            headers={"Content-Disposition": f'attachment; filename="{ds.name}.json"'},
        )
    else:
        buf = io.StringIO()
        df.to_csv(buf, index=False)
        return StreamingResponse(
            io.BytesIO(buf.getvalue().encode("utf-8")),
            media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{ds.name}.csv"'},
        )


@router.get("/report/{report_id}")
async def export_report(
    report_id: str,
    format: str = Query("md", description="md or json"),
    user: CurrentUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Download a report as Markdown or JSON."""
    result = await db.execute(
        select(Report).where(Report.id == report_id, Report.org_id == user.org_id)
    )
    report = result.scalar_one_or_none()
    if not report:
        raise HTTPException(404, "Report not found")

    await record_audit(db, user.org_id, user.user_id, "export", "report", report_id, f"format={format}")
    await db.commit()

    if format == "json":
        data = json.dumps({
            "id": report.id,
            "type": report.report_type,
            "title": report.title,
            "content": report.content,
            "created_at": str(report.created_at),
        }, indent=2)
        return StreamingResponse(
            io.BytesIO(data.encode("utf-8")),
            media_type="application/json",
            headers={"Content-Disposition": f'attachment; filename="{report.title}.json"'},
        )
    else:
        md = f"# {report.title}\n\n{report.content}\n\n---\n*Generated by Kapi on {report.created_at}*\n"
        return StreamingResponse(
            io.BytesIO(md.encode("utf-8")),
            media_type="text/markdown",
            headers={"Content-Disposition": f'attachment; filename="{report.title}.md"'},
        )


@router.get("/insight/{insight_id}")
async def export_insight(
    insight_id: str,
    user: CurrentUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Download an insight analysis as JSON."""
    result = await db.execute(
        select(InsightResult).where(InsightResult.id == insight_id, InsightResult.org_id == user.org_id)
    )
    ins = result.scalar_one_or_none()
    if not ins:
        raise HTTPException(404, "Insight not found")

    await record_audit(db, user.org_id, user.user_id, "export", "insight", insight_id)
    await db.commit()

    data = json.dumps({
        "id": ins.id,
        "mode": ins.mode,
        "title": ins.title,
        "metrics": ins.metrics,
        "findings": ins.findings,
        "problems": ins.problems,
        "recommendations": ins.recommendations,
        "ai_summary": ins.ai_summary,
        "waste": ins.waste,
        "opportunities": ins.opportunities,
        "created_at": str(ins.created_at),
    }, indent=2)
    return StreamingResponse(
        io.BytesIO(data.encode("utf-8")),
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="insight-{ins.mode}.json"'},
    )


@router.get("/audit-log")
async def export_audit_log(
    limit: int = Query(500, le=5000),
    user: CurrentUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Download the audit log for the current org."""
    result = await db.execute(
        select(AuditLog)
        .where(AuditLog.org_id == user.org_id)
        .order_by(AuditLog.created_at.desc())
        .limit(limit)
    )
    rows = result.scalars().all()

    data = json.dumps([
        {
            "timestamp": str(r.created_at),
            "user_id": r.user_id,
            "action": r.action,
            "resource_type": r.resource_type,
            "resource_id": r.resource_id,
            "details": r.details,
        }
        for r in rows
    ], indent=2)

    return StreamingResponse(
        io.BytesIO(data.encode("utf-8")),
        media_type="application/json",
        headers={"Content-Disposition": 'attachment; filename="kapi-audit-log.json"'},
    )
